### ISSUE TITLE
install question nsupported config option for services:'Web‘ 

### ISSUE THREAD

**Issue by adminnano** [2740908911/Pilot-Web#3]
my environment is centos 7.6 
other environment is root@192 
Docker version 26.1.3, build b72abbb
docker-compose version 1.18.0, build 8dd22a9
how to deal this problems?

**Comment by 2740908911** [comment]
Docker Compose版本过低。建议升级您的Docker Compose版本。用于测试和编写pilot的最低版本为1.29.2。有关升级和版本不兼容的问题，请参阅以下文章https://www.cnblogs.com/flyskyzero/p/16700331.html
The Docker Compose version is too low. It is recommended to upgrade your Docker Compose version. The minimum version used for testing and writing the pilot is 1.29.2. For issues related to upgrading and version incompatibility, please refer to the following article https://www.cnblogs.com/flyskyzero/p/16700331.html
