### ISSUE TITLE
有关开发

### ISSUE THREAD

**Issue by Curious-L** [2740908911/Pilot-Web#4]
你好，项目很不错！但我想请问一下，怎么对其进行开发环境的部署，以便于自定义修改项目。（送花）

**Comment by 2740908911** [comment]
如果您只需要简单的修改部分内容，可以参考以下内容：
靶场的静态页面存放在pilot-client文件夹，Flask代码存放在pilot-server文件夹，您可以根据特定的URL对文件内容或python代码进行修改，然后使用init.sh脚本追加-cld参数重构靶场。自定义修改内容需要对前后端代码编程有一定的学习和了解，错误的修改会导致服务崩溃。

如果您需要新添加特定的漏洞环境，由于开发和学习成本过高，暂不提供开发环境的部署以及自定义开发教程。
自定义开发需要一定的技术成本，建议您可以提出需求我会抽空完善项目。

**Comment by Curious-L** [comment]
okay! Thank you very much!
